<?php

namespace ContainerPg5yA3r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBidManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\BidManager' shared autowired service.
     *
     * @return \App\Service\BidManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/BidManager.php';

        return $container->privates['App\\Service\\BidManager'] = new \App\Service\BidManager();
    }
}
