<?php

namespace ContainerLBcusCJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SessionManager' shared autowired service.
     *
     * @return \App\Service\SessionManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/SessionManager.php';

        return $container->privates['App\\Service\\SessionManager'] = new \App\Service\SessionManager();
    }
}
