<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWEItoVQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWEItoVQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWEItoVQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWEItoVQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWEItoVQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'WEItoVQ',
    'container.build_id' => '3d7dab78',
    'container.build_time' => 1746122397,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWEItoVQ');
