<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ1xEwtW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ1xEwtW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ1xEwtW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ1xEwtW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ1xEwtW\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q1xEwtW',
    'container.build_id' => '9e7908dc',
    'container.build_time' => 1747573135,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ1xEwtW');
