<?php

namespace ContainerZoFEZgw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_PWTGk2CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.PWTGk2C' shared service.
     *
     * @return \App\Controller\BidManager
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\BidController::postBid()": the $bidManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\BidManager". Did you forget to add a use statement?');
    }
}
