<?php

namespace ContainerZoFEZgw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3YULB5YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3YULB5Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3YULB5Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sessionManager' => ['privates', '.errored.LElM6E_', NULL, 'Cannot determine controller argument for "App\\Controller\\BidController::postBid()": the $sessionManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\SessionManager". Did you forget to add a use statement?'],
            'bidManager' => ['privates', '.errored.PWTGk2C', NULL, 'Cannot determine controller argument for "App\\Controller\\BidController::postBid()": the $bidManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\BidManager". Did you forget to add a use statement?'],
        ], [
            'sessionManager' => '?',
            'bidManager' => '?',
        ]);
    }
}
